version: "2"
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
    volumes:
      - home:/home
      - jenkins_data:/var/jenkins
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  home:
  jenkins_data:
